server:
  port: 8762
  tomcat:
    max-threads: 500
spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://172.16.0.199:8761/eureka/
    #    defaultZone: http://localhost:8761/eureka/
  instance: #eureka server 页面列表字段 status 显示ip
      prefer-ip-address: true
      instance-id: ${spring.cloud.client.ip-address}:${server.port}

zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  prefix: /api
  routes:
    api-identity:
      path: /identity/**
      serviceId: api-identity
      sensitive-headers:
      custom-sensitive-headers: true
    api-company:
      path: /company/**
      serviceId: api-company
      sensitive-headers:
      custom-sensitive-headers: true
  host:
    max-per-route-connections: 1000
    max-total-connections: 2000
  semaphore:
    max-semaphores: 5000
#  sensitive-headers:

ribbon:
  ReadTimeout: 100000  # 单位毫秒数
  SocketTimeout: 100000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 250000
  threadpool:
    default:
      coreSize=500: